### ISSUE TITLE
Send collected metrics and logs to InfluxDB

### ISSUE THREAD

**Issue by swapbyt3s** [swapbyt3s/zenit#4]
Project:
https://github.com/influxdata/influxdb/tree/master/client/v2

**Comment by mjf** [comment]
Also logs can be send to *InfluxDB*.

**Comment by swapbyt3s** [comment]
Related documentation: https://www.influxdata.com/blog/telegraf-correlate-log-metrics-data-performance-bottlenecks/

**Comment by nstrappazzonc** [comment]
Done
