### ISSUE TITLE
Allow multiple Servers

### ISSUE THREAD

**Issue by swapbyt3s** [swapbyt3s/zenit#50]
With this feature, is possible with one daemon access to multiple servers, for example RDS / Aurora.

Functionalities for multiple servers:
- MySQL
- ProxySQL

The logging parsing files is imposible, in the case for RDS or other service type require different method to process it.

**Comment by nstrappazzonc** [comment]
With this feature, is possible with one daemon access to multiple servers, for example RDS / Aurora.

Functionalities for multiple servers:
- MySQL
- ProxySQL

**Comment by nstrappazzonc** [comment]
Is done
